export const SELECT_LOCATION = 'SELECT_LOCATION';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GUIDE_VIEWED = 'GUIDE_VIEWED';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const INCREASE_BASKET_ITEM = 'INCREASE_BASKET_ITEM';
export const DECREASE_BASKET_ITEM = 'DECREASE_BASKET_ITEM';
export const DELETE_BASKET_ITEM = 'DELETE_BASKET_ITEM';
export const INIT_MENU = 'INIT_MENU';
export const CHANGED_AVATAR = 'CHANGED_AVATAR';
export const CHANGED_BIRTHDAY = 'CHANGED_BIRTHDAY';
export const CHANGED_FIO = 'CHANGED_FIO';
export const CHANGED_PHONE = 'CHANGED_PHONE';
export const CHANGED_EMAIL = 'CHANGED_EMAIL';

