export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const BACK = 'BACK';
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_USER_FAILURE = 'NEW_USER_FAILURE';

export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';
export const START_REQUEST = 'START_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const SUBMITTING_START = 'SUBMITTING_START';
export const SUBMITTING_STOP = 'SUBMITTING_STOP';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const GET_TASKS_BY_DAY = 'GET_TASKS_BY_DAY';
export const FETCH_NEWSES_SUCCESS = 'FETCH_NEWSES_SUCCESS';
