/**
 * Default translation for 'en_EN' language
 */

export const en = {
	selectLanguage: 'Select language',
	next: 'Next',
	run: 'Go!',
	youAreNotLoggedIn: 'You are not logged in',
	loginOrRegister: 'Log in with your account or register',
	enterOrRegister: 'Enter or register',
	loginText: 'Phone number, e-mail or login',
	fioLabel: 'Your first and last name:',
	fioPlaceholder: 'eg: Kaliev Kanybek',
	phoneExamplePlaceholder: 'eg: 555 55-55-55',
	emailLabel: 'Your email:',
	emailPlaceholder: 'eg: example@gmail.com',
	phoneLabel: 'Your phone number:',
	birthdayDate: 'Date of Birth:',
	doneBtnLabel: 'Select',
	cancelBtnLabel: 'Cancel',
	save: 'Save',
	password: 'Password',
	remind: 'Remind me',
	signIn: 'Sign in',
	signUp: 'Sign up',
	enter: 'Sign in',
	enterYourPhone: 'Enter your \n phone number',
	SmsInfo: 'After that, an SMS with an authorization code will be sent to the phone number you specified for confirmation.',
	toBasket: 'Add to cart',
	clearBasket: 'Clear',
	order: 'Order at \${sum} ⊆',
	addItemsToBasket: 'Add items to basket',
	freeShipping: 'free shipping',
	shippingPrice: 'Shipping price: \${price} ⊆',
	itemsInBasket: 'Items in basket: \${totalAmount}',
	numberOfContainers: 'Number of containers: \${amount}',
	containersPrice: 'The price of containers: \${price}',
	navigateToMenu: 'Go to menu',
	exitFromApp: 'Exit from application',
	tabbar: {
		Home: 'Home',
		Menu: 'Menu',
		PersonalArea: 'Personal Area',
		Search: 'Search',
		Basket: 'Basket',
	},
	navigationTitle: {
		Branches: 'Our establishments',
		PopularDishes: 'Popular dishes',
		Profile: 'Personal Area',
		Auth: 'Personal Area',
		PersonalData: 'Your data',
		Terms: 'Terms of Use',
		PrivacyPolicy: 'Privacy policy',
		Settings: 'Settings',
		Help: 'Help',
		MyCards: 'Your cards',
		MyAddresses: 'Your addresses',
	},
	cardHolderName: 'Cardholder\'s name',
	cardNumber: 'Card number:',
	expiry: 'Expiry date:',
	cvc: 'CVS Code:',
	cvcPlaceholder: '3-4 digits',
	cardIsExist: 'Card is exist!',
	deleteThisCard: 'Are you sure you want to delete this card?',
	deleteThisAddress: 'Are you sure you want to delete this address?',
	defaultCard: 'This card is already the default card.',
	cancel: 'Cancel',
	delete: 'Delete',
	swipeLeftDescription: 'Swipe to the left on the card opens the action menu.',
	swipeRightDescription: 'Swipe to the right on the card opens the action menu.',
	addCard: 'Add card',
	saveCard: 'Save card',
	emptySearch: 'Nothing found',
	enterDishName: 'Enter the name of the dish',
	addAddress: 'Add addresses',
	saveAddress: 'Save addresses',
	home: 'Home',
	office: 'Office',
	address: 'Address',
	addressNotes: 'Notes',
	addressPlaceholder: 'eg, microdistrict. 11, building 12, apt. 55',
	addressNotesPlaceholder: 'staircase, floor, lock code ...',
	pay: 'To pay',
	name: 'Your name:',
	phone: 'Your phone:',
};
