/**
 * Default translation for 'kk_KZ' language
 */

export const kz = {
	selectLanguage: 'Тілді таңдаңыз',
	next: 'келесі',
	run: 'барыңыз!',
	youAreNotLoggedIn: 'сіз авторизацияланған емес',
	loginOrRegister: 'тіркелгіңізге кіріңіз немесе тіркеліңіз',
	enterOrRegister: 'кіру немесе тіркелу',
	loginText: 'телефон нөмірі, e-mail немесе логин',
	fioLabel: 'аты және Тегі:',
	fioPlaceholder: 'мысалы: Kaliev Kanybek',
	phonePlaceholder: 'мысалы: 555 55-55-55',
	emailLabel: 'сіздің пошта:',
	emailPlaceholder: 'мысалы: example@gmail.com',
	phoneLabel: 'сіздің телефоныңыз:',
	birthdayDate: 'туған күні:',
	doneBtnLabel: 'таңдау',
	cancelBtnLabel: 'болдырмау',
	save: 'сақтау',
	password: 'Құпия сөз',
	remind: 'еске салу',
	signIn: 'кіру',
	signUp: 'Тіркелу',
	enter: 'кіру',
	enterYourPhone: 'сіздің \N телефон нөміріңізді енгізіңіз',
	SmsInfo: 'осыдан кейін сіз көрсеткен телефон нөміріне растау үшін авторландыру коды бар SMS келеді.',
	toBasket:'себетке',
	clearBasket: 'тазарту',
	order: '\${sum} құрылғыға тапсырыс ресімдеу',
	addItemsToBasket: 'себетке тауарларды қосыңыз',
	freeShipping: 'Жеткізу құны: ',
	shippingPrice: 'жеткізу бағасы: \ $ {price}',
	itemsInBasket: 'себетте тауарлар: \ $ {totalAmount}',
	numberOfContainers: 'бір реттік ыдыс-аяқ және контейнерлер: \ $ {amount}',
	containersPrice: 'ыдыс бағасы: \ $ {price}',
	navigateToMenu: 'мәзірге өту',
	exitFromApp: 'қолданбадан шығу',
	tabbar: {
		Home: 'Басты',
		Menu: 'Мәзір',
		PersonalArea: 'Жеке Кабинет',
		Search: 'Іздеу',
		Basket: 'Себет',
	},
	navigationTitle: {
		Branches: 'біздің мекемелер',
		PopularDishes: 'танымал тағамдар',
		Profile: 'Жеке Кабинет',
		Auth: 'Жеке Кабинет',
		PersonalData: 'сіздің деректер',
		Terms: 'пайдалану шарттары',
		PrivacyPolicy: 'құпиялылық саясаты',
		Settings: 'Параметрлер',
		Help: 'Көмек',
		MyCards: 'сіздің карталар',
		MyAddresses: 'Сіздің мекен-жайыңыз',
	},
	cardHolderName: 'аты картадан:',
	cardNumber: 'карта нөмірі:',
	expiry: 'аяқтау күні:',
	cvc: 'CVS коды:',
	cvcPlaceholder: '3-4 сандар',
	cardIsExist: 'мұндай карта бар!',
	deleteThisCard: 'сіз осы картаны жойғыңыз келе ме?',
	deleteThisAddress: 'сіз осы мекенжайды жойғыңыз келе ме?',
	defaultCard: 'бұл карта әдепкі карта болып табылады.',
	cancel: 'жою',
	delete: 'жою',
	swipeLeftDescription: 'Свайп солға карточка бойынша әрекеттер мәзірін ашады.',
	swipeRightDescription: 'карта бойынша оңға қада Әрекеттер мәзірін ашады.',
	addCard: 'картаны қосу',
	saveCard: 'картаны сақтау',
	emptySearch: 'ештеңе табылмады',
	enterDishName: "тағамның атауын енгізіңіз",
	addAddress: 'адрестерді қосу',
	saveAddress: 'адрестерді сақтау',
	home: 'үй',
	office: 'жұмыс',
	address: 'мекенжай',
	addressNotes: 'жазбалар',
	addressPlaceholder: 'мысалы, ш / а. 11 үй, 12 үй, 55 пәтер',
	addressNotesPlaceholder: 'кіреберіс, қабат, құлып коды...',
	pay: 'Оплптить',
	name: 'атыңыз:',
	phone: 'сіздің телефоныңыз:',
	checkout: 'тапсырысты ресімдеу',
	fillRequiredFields: 'міндетті өрістерді толтырыңыз',
	showAll: 'барлығын көрсету',
	orderAccepted: 'сіздің тапсырыс қабылданған',
	returnToHome: 'жалтыраққа оралу',
	orderNumber: 'тапсырыс нөмірі:',
	portion: 'Порция',
	pc: '1 дана',
	back: 'артқа',
	billingInformation: 'төлем ақпараты',
	addYourCard: 'сіздің төлем картаңызды қосыңыз',
	deliveryAddresses: 'жеткізу мекенжайы',
	addYourAddresses: 'мекенжайыңызды қосыңыз немесе жояды',
	bringFriend: "Досыңды келтір",
	getGift: '500 сом сыйлыққа алыңыз',
	supportService: 'қолдау қызметі',
	settings: 'Параметрлер',
	termsOfUse: 'пайдалану шарттары',
	privacyPolicy: 'құпиялылық саясаты',
	commentsSuggestions: 'пікірлер мен ұсыныстар:',
	deliveryService: 'жеткізу қызметі:',
	yourDiscount: 'сіздің жеңілдік',
	fillYourDetails: 'сіздің деректеріңізді толтырыңыз',
	pushNotifications: 'push хабарламалар',
	pushNotificationsDescription:'жеткізу мәртебесі, курьерден хабарлар',
	emailNewsletter: 'Email тарату',
	emailNewsletterDescription:'жеткізу мәртебесі, курьерден хабарлар',
	yourCity: 'сіздің қалаңыз',
	selectedCity: 'таңдалған: \ $ {city}',
	languageSelection: 'Тілді таңдау',
	getCode: 'Кодты алу',
};
