/**
 * Default translation for 'ru_RU' language
 */

export const ru = {
	selectLanguage: 'Выберите язык',
	next: 'Далее',
	run: 'Поехали!',
	youAreNotLoggedIn: 'Вы не авторизированы',
	loginOrRegister: 'Войдите под своим аккаунтом или зарегистрируйтесь',
	enterOrRegister: 'Войти или зарегистрироваться',
	loginText: 'Номер телефона, e-mail или логин',
	fioLabel: 'Ваше имя и фамилия:',
	fioPlaceholder: 'например: Kaliev Kanybek',
	phonePlaceholder: 'например: 555 55-55-55',
	emailLabel: 'Ваша почта:',
	emailPlaceholder: 'например: example@gmail.com',
	phoneLabel: 'Ваш телефон:',
	birthdayDate: 'Дата рождения:',
	doneBtnLabel: 'Выбрать',
	cancelBtnLabel: 'Отменить',
	save: 'Сохранить',
	password: 'Пароль',
	remind: 'Напомнить',
	signIn: 'Войти',
	signUp: 'Зарегистрироваться',
	enter: 'Вход',
	enterYourPhone: 'Введите ваш \n номер телефона',
	SmsInfo: 'После этого на указанный Вами номер телефона придет СМС с кодом авторизации для подтверждения.',
	toBasket: 'В корзину',
	clearBasket: 'Очистить',
	order: 'Оформить заказ на \${sum} ₸',
	addItemsToBasket: 'Добавьте товары в корзину',
	freeShipping: 'Стоимость доставки: ',
	shippingPrice: 'Цена доставки: \${price} ₸',
	itemsInBasket: 'Товаров в корзине: \${totalAmount}',
	numberOfContainers: 'Одноразовая посуда и контейнеры: \${amount}',
	containersPrice: 'Цена посуды: \${price}',
	navigateToMenu: 'Перейти в меню',
	exitFromApp: 'Выйти из приложения',
	tabbar: {
		Home: 'Главная',
		Menu: 'Меню',
		PersonalArea: 'Личный Кабинет',
		Search: 'Поиск',
		Basket: 'Корзина',
	},
	navigationTitle: {
		Branches: 'Наши заведения',
		PopularDishes: 'Популярные блюда',
		Profile: 'Личный Кабинет',
		Auth: 'Личный Кабинет',
		PersonalData: 'Ваши данные',
		Terms: 'Условия использования',
		PrivacyPolicy: 'Политика конфиденциальности',
		Settings: 'Настройки',
		Help: 'Помощь',
		MyCards: 'Ваши карты',
		MyAddresses: 'Ваши адреса',
	},
	cardHolderName: 'Имя на карте:',
	cardNumber: 'Номер карты:',
	expiry: 'Дата окончания:',
	cvc: 'Код CVS:',
	cvcPlaceholder: '3-4 цифры',
	cardIsExist: 'Такая карта уже существует!',
	deleteThisCard: 'Вы уверены что хотите удалить эту карту?',
	deleteThisAddress: 'Вы уверены что хотите удалить этот адрес?',
	defaultCard: 'Эта карта уже является Картой по умолчанию.',
	cancel: 'Отмена',
	delete: 'Удалить',
	swipeLeftDescription: 'Свайп влево по карточке открывает меню действий.',
	swipeRightDescription: 'Свайп вправо по карточке открывает меню действий.',
	addCard: 'Добавить карту',
	saveCard: 'Сохранить карту',
	emptySearch: 'Ничего не найдено',
	enterDishName: 'Введите название блюда',
	addAddress: 'Добавить адреса',
	saveAddress: 'Сохранить адреса',
	home: 'Дом',
	office: 'Работа',
	address: 'Адрес:',
	addressNotes: 'Заметки:',
	addressPlaceholder: 'например,  мкрн. 11, дом 12, кв. 55',
	addressNotesPlaceholder: 'подъезд, этаж, код от замка...',
	emailAddressPlaceholder: 'example@mail.ru',
	emailAddress: 'Ваш e-mail:',
	pay: 'Оплатить',
	name: 'Ваше имя:',
	phone: 'Ваш телефон:',
	checkout: 'Оформить заказ',
	fillRequiredFields: 'Заполните обязательные поля',
	showAll: 'Показать все',
	orderAccepted: 'Ваш заказ принят',
	returnToHome: 'Вернуться на гланую',
	orderNumber: 'Номер заказа:',
	portion: 'Порция',
	pc: '1 шт',
	back: 'Назад',
	billingInformation: 'Платежная информация',
	addYourCard: 'Добавьте свою платежную карту',
	deliveryAddresses: 'Адреса доставки',
	addYourAddresses: 'Добавляйте или удаляте ваши адреса',
	bringFriend: 'Приведи друга',
	getGift: 'Получи 500 сом в подарок',
	supportService: 'Служба поддержки',
	settings: 'Настройки',
	termsOfUse: 'Условия использования',
	privacyPolicy: 'Политика конфиденциальности',
	commentsSuggestions: 'Отзывы и предложения:',
	deliveryService: 'Служба доставки:',
	yourDiscount: 'Ваша скидка',
	fillYourDetails: 'Заполните ваши данные',
	pushNotifications: 'PUSH уведомления',
	pushNotificationsDescription: 'Статус доставки, сообщения от курьера',
	emailNewsletter: 'Email рассылка',
	emailNewsletterDescription: 'Статус доставки, сообщения от курьера',
	yourCity: 'Ваш город',
	selectedCity: 'Выбран: \${city}',
	languageSelection: 'Выбор языка',
	getCode: 'Получить код',
};
