/**
 * Default translation for 'ru_RU' language
 */

export const ru = {
	selectLanguage: 'Выберите язык',
	next: 'Далее',
	run: 'Поехали!',
	youAreNotLoggedIn: 'Вы не авторизированы',
	loginOrRegister: 'Войдите под своим аккаунтом или зарегистрируйтесь',
	enterOrRegister: 'Войти или зарегистрироваться',
	loginText: 'Номер телефона, e-mail или логин',
	fioLabel: 'Ваше имя и фамилия:',
	fioPlaceholder: 'например: Kaliev Kanybek',
	phonePlaceholder: 'например: 555 55-55-55',
	emailLabel: 'Ваша почта:',
	emailPlaceholder: 'например: example@gmail.com',
	phoneLabel: 'Ваш телефон:',
	birthdayDate: 'Дата рождения:',
	doneBtnLabel: 'Выбрать',
	cancelBtnLabel: 'Отменить',
	save: 'Сохранить',
	password: 'Пароль',
	remind: 'Напомнить',
	signIn: 'Войти',
	signUp: 'Зарегистрироваться',
	enter: 'Вход',
	enterYourPhone: 'Введите ваш \n номер телефона',
	SmsInfo: 'После этого на указанный Вами номер телефона придет СМС с кодом авторизации для подтверждения.',
	toBasket: 'В корзину',
	clearBasket: 'Очистить',
	order: 'Оформить заказ на \${sum} ⊆',
	addItemsToBasket: 'Добавьте товары в корзину',
	freeShipping: 'Бесплатная доставка',
	shippingPrice: 'Цена доставки: \${price} ⊆',
	itemsInBasket: 'Товаров в корзине: \${totalAmount}',
	numberOfContainers: 'Одноразовая посуда и контейнеры: \${amount}',
	containersPrice: 'Цена посуды: \${price}',
	navigateToMenu: 'Перейти в меню',
	exitFromApp: 'Выйти из приложения',
	tabbar: {
		Home: 'Главная',
		Menu: 'Меню',
		PersonalArea: 'Личный Кабинет',
		Search: 'Поиск',
		Basket: 'Корзина',
	},
	navigationTitle: {
		Branches: 'Наши заведения',
		PopularDishes: 'Популярные блюда',
		Profile: 'Личный Кабинет',
		Auth: 'Личный Кабинет',
		PersonalData: 'Ваши данные',
		Terms: 'Условия использования',
		PrivacyPolicy: 'Политика конфиденциальности',
		Settings: 'Настройки',
		Help: 'Помощь',
		MyCards: 'Ваши карты',
	},
	cardHolderName: 'Имя на карте:',
	cardNumber: 'Номер карты:',
	expiry: 'Дата окончания:',
	cvc: 'Код CVS:',
	cvcPlaceholder: '3-4 цифры',
};
